std_msgs/Header header

float64 roll
float64 pitch
float64 azimuth
float64 top_velocity_x
float64 top_velocity_y
float64 top_velocity_z
float64 table_x
float64 table_y
float64 table_z
float64 latitude
float64 longitude
float64 height
float64 north_velocity
float64 east_velocity
float64 down_velocity
float64 gps_state

float64 gps_time
uint8 rotation_type
float64 gps_zhou

uint8 Initializing_State
